const defaultMenu = {
  "Paneer Curries": ["Paneer Butter Masala","Paneer Lababdar","Paneer Bheda Fry","Paneer Kali Mirch","Paneer Kaleji","Shahi Paneer","Paneer Handi Kofta","Paneer Matar Masala","Paneer Changezi","Paneer Tikka Masala","Paneer Hyderabadi","Paneer Do Pyaza","Paneer Cheese Gotala","Cheese Butter Masala","Palak Paneer","Achari Paneer","Paneer Cheese Kofta","Paneer Angara","Cheese Angoori","Paneer Kadai","Paneer Chatpata","Sham Savera Kofta Curry","Paneer Toofani","Paneer Bhurji","Paneer Lehsuni","Paneer Kaju Masala","Malai Kofta","Paneer Patiala","Paneer Khurchan","Lehsuni Palak Paneer"],
  "Vegetable Mains": ["Sev Turai","Kaju Karela","Punjabi Parwal","Undhiyu","Dana Muthiya","Lasaniya Bataka","Bataka Nu Khatiyu","Bharela Karela","Dudhi Chana","Turiya Patra","Aloo Gobhi","Bharela Bhinda","Bhinda Capsicum","Sev Tomato","Ringan Bataka","Panchkutiyu Shaak","Baingan Ka Bharta","Bhindi Dahiwala","Jeera Aloo","Tuver Na Totha","Papdi Lilva Nu Shaak","Veg Kofta","Kaju Makhani Sabji","Lehsuni Aloo Palak","Veg Kheema Masala","Veg Bhuna Handi","Aloo Methi Masala","Methi Matar Malai","Veg Kolhapuri","Corn Capsicum Bharta","Kashmiri Dum Aloo","Bhindi Do Pyaza","Rajma Masala","Chhole Masala","Veg Diwani Handi","Mushroom Masala","Veg Jaipuri","Chana Palak Masala","Palak Cheese Corn","Veg Jalfrezi","Dum Aloo Punjabi","Rajasthani Gatte Masala"],
  "Tandoor & Starters": ["Paneer Tikka","Lehsuni Paneer Tikka","Pahadi Hariyali Paneer Tikka","Kali Mirch Paneer Tikka","Peri Peri Paneer Tikka","Malai Paneer Tikka","Mushroom Tikka","Basil Paneer Tikka","Tandoori Soya Chaap","Afghani Soya Chaap","Malai Soya Chaap","Pizza Chaap","Pahadi Chaap","Peri Peri Chaap","Lemon Pepper Chaap","Cream Onion Chaap","Schezwan Chaap","Kali Mirch Chaap","Garlic Chaap","Tandoori Stuffed Chaap","Hara Bhara Kabab","Veg Seekh Kabab","Paneer Kabab","Pineapple Paneer Tikka"],
  "Indo-Chinese & Global": ["Paneer Chilli","Mushroom Chilli","Schezwan Paneer","Schezwan Mushroom","Paneer 65","Potato Honey Chilli","Veg Crispy","Basil Pesto Rice","Paneer Thai Curry","Kung Pao Paneer Hot Pot","Paneer Majestic","Dragon Paneer","Mongolian Paneer","Malaysian Paneer","Hunan Style Paneer","Veg Fried Rice","Smoky Tomato Rice","Crispy Corn Fried Rice","Burnt Chilli Garlic Fried Rice","Exotic Veggies with Schezwan Sauce","Crispy Chilli Potato","Mexican Rice with Paprika Curry","Italian Pesto Fried Rice","Schezwan Fried Rice","Spinach Rice with Paprika Curry","Hot Pot Paneer Rice"],
  "Rice, Dal & Comfort": ["Papdi Lilva No Pulav","Palak Paneer Pulav","Achari Chhole Pulav","Puri","Rotali","Paratha","Kulcha","Dal Tadka","Dal Makhni","Jeera Rice & Dal Tadka","Dal Palak","Gujarati Badamaniya Dal","Lucknowi Dal Bhat Kadhi","Veg Paneer Pulao","Tawa Pulao with Garlic Chutney","Navratan Pulao","Lemon Rice","Dhansek Dal Chawal","Gujarati Dal Bhat","Paneer Tikka Dum Biryani","Paneer Makhni Biryani","Soya Chaap Dum Biryani","Idli Sambhar","Medu Vada Sambhar","Chhole Bhature","Alfredo Pasta","Pink Sauce Pasta","Red Sauce Pasta","Dal Masala Khichdi Kadhi","Lasooni Palak Khichdi Kadhi","Misal Pav","Usal Pav"],
  "Street Food & Bites": ["Red Pav Bhaji","Green Pav Bhaji","Gotala Pav Bhaji","Tapela Pav Bhaji","Black Pav Bhaji","Jain Pav Bhaji","Cheese Puff","Vatana Puff","Mexican Puff","Disco Patra","Veg Puff","Russian Roll","Matar Kachori","Tomato Pakora","Jalapeno Paneer Pockets","Cheese Corn Balls","Bread Roll","Ponk Vada","Crispy Onion Samosa","Kanda Bhajiya","Lilva Na Vada","Ratalu Pettis","Bread Pakora","Paneer Sandwich Dhokla","Mushroom Samosa","Veg Samosa","Falafel","Corn Paneer Samosa","Crispy Paneer Roll","Cheese Paneer Cigar","Live Dhokla","Paneer Cheese Lifafa","Paneer Chilli Puff","Crispy Cheese Balls","Veg Spring Rolls","Chinese Samosa","Pizza Puff","Paneer Cheese Kurkure","Cheesy Pizza Bomb","Paneer Tikka Finger","Corn Spinach Cheese Roll","Veg Railway Style Cutlet","Cheesy Bread Roll","Dal Vada","Punjabi Samosa","Bihari Samosa","Paneer Poppers","Khata Dhokla"]
};
function normalizeMenu(source){return Object.fromEntries(Object.entries(source).map(([category,dishes])=>[category,dishes.map(dish=>typeof dish==="string"?{name:dish,description:""}:dish)]))}
let menu=normalizeMenu(JSON.parse(localStorage.getItem("vk_menu")||"null")||structuredClone(defaultMenu));
let items=[];
const isHosted=location.protocol==="https:"||location.protocol==="http:";
let active="All dishes";
const pageSize=12;
let visibleLimit=pageSize;
const grid=document.querySelector("#menuGrid"),tabs=document.querySelector("#tabs"),search=document.querySelector("#search"),count=document.querySelector("#count");
function drawTabs(){["All dishes",...Object.keys(menu)].forEach(category=>{const button=document.createElement("button");button.textContent=category;button.className=category===active?"active":"";button.onclick=()=>{active=category;visibleLimit=pageSize;refreshTabs();drawMenu()};tabs.appendChild(button)})}
function rebuildItems(){items=Object.entries(menu).flatMap(([category,dishes])=>dishes.map(dish=>({...dish,category,searchText:`${dish.name} ${dish.description||""} ${category}`.toLocaleLowerCase()})))}
function saveMenu(){localStorage.setItem("vk_menu",JSON.stringify(menu));rebuildItems();if(active!=="All dishes"&&!menu[active])active="All dishes";refreshTabs();drawMenu();drawAdmin();pushOnlineMenu()}
async function pushOnlineMenu(){if(!isHosted||sessionStorage.getItem("vk_admin")!=="yes")return;const response=await fetch("/api/menu",{method:"PUT",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({menu})});if(!response.ok)alert("The menu was saved on this device but could not be updated online. Please sign in again.")}
async function pullOnlineMenu(){if(!isHosted)return;try{const response=await fetch("/api/menu");if(response.ok){const data=await response.json();if(data.menu&&Object.keys(data.menu).length){menu=normalizeMenu(data.menu);localStorage.setItem("vk_menu",JSON.stringify(menu));rebuildItems();refreshTabs();drawMenu()}}}catch(error){console.warn("Using the local menu copy.")}}
function drawMenu(){const query=search.value.trim().toLocaleLowerCase();const matches=items.filter(item=>(active==="All dishes"||item.category===active)&&(!query||item.searchText.includes(query)));const visible=matches.slice(0,visibleLimit);count.textContent=`Showing ${visible.length} of ${matches.length}`;grid.innerHTML=visible.map(item=>`<article class="dish"><small>${item.category}</small><h3>${item.name}</h3>${item.description?`<p>${item.description}</p>`:""}</article>`).join("")||"<p>No dishes found. Try another search.</p>";const more=document.querySelector("#loadMore");more.hidden=visible.length>=matches.length;more.textContent=`Show ${Math.min(pageSize,matches.length-visible.length)} more dishes`}
function refreshTabs(){tabs.innerHTML="";drawTabs()}
let searchFrame=0;search.addEventListener("input",()=>{visibleLimit=pageSize;cancelAnimationFrame(searchFrame);searchFrame=requestAnimationFrame(drawMenu)});document.querySelector("#loadMore").onclick=()=>{visibleLimit+=pageSize;drawMenu()};document.querySelector("#year").textContent=new Date().getFullYear();rebuildItems();refreshTabs();drawMenu();pullOnlineMenu();

const modal=document.querySelector("#adminModal"),loginView=document.querySelector("#adminLogin"),panel=document.querySelector("#adminPanel"),categorySelect=document.querySelector("#dishCategory"),adminList=document.querySelector("#adminCategoryList");
const adminButton=document.querySelector("#openAdmin");let sessionTimer=0;
function setAdminIdentity(name=""){adminButton.textContent=name||"Admin login";adminButton.classList.toggle("signed-in",Boolean(name));if(name)sessionStorage.setItem("vk_admin_name",name);else sessionStorage.removeItem("vk_admin_name")}
function scheduleSessionEnd(expires){clearTimeout(sessionTimer);const remaining=Number(expires)-Date.now();if(remaining>0)sessionTimer=setTimeout(()=>{sessionStorage.removeItem("vk_admin");setAdminIdentity();showAdmin()},remaining);else{sessionStorage.removeItem("vk_admin");setAdminIdentity()}}
async function syncAdminSession(){if(!isHosted){setAdminIdentity();return}try{const response=await fetch("/api/auth",{credentials:"same-origin"}),data=await response.json();if(data.authenticated){sessionStorage.setItem("vk_admin","yes");setAdminIdentity(data.name);scheduleSessionEnd(data.expires)}else{sessionStorage.removeItem("vk_admin");setAdminIdentity()}}catch{sessionStorage.removeItem("vk_admin");setAdminIdentity()}}
function showAdmin(){const signedIn=sessionStorage.getItem("vk_admin")==="yes";loginView.hidden=signedIn;panel.hidden=!signedIn;if(signedIn)drawAdmin()}
function drawAdmin(){if(panel.hidden)return;const previousCategory=categorySelect.value;categorySelect.replaceChildren(...Object.keys(menu).map(category=>{const option=document.createElement("option");option.value=category;option.textContent=category;return option}));if(previousCategory&&menu[previousCategory])categorySelect.value=previousCategory;else if(categorySelect.options.length)categorySelect.selectedIndex=0;adminList.innerHTML=Object.entries(menu).map(([category,dishes])=>`<section class="manage-category"><div class="manage-category-head"><div><b>${category}</b><small>${dishes.length} dishes</small></div><div><button data-delete-category="${category}">Delete category</button></div></div><div class="manage-dishes">${dishes.map(dish=>`<span><b>${dish.name}</b>${dish.description?`<small>${dish.description}</small>`:"<small>No description yet</small>"}<button data-edit-dish="${category}|${dish.name}">Edit</button><button data-delete-dish="${category}|${dish.name}" aria-label="Remove ${dish.name}">×</button></span>`).join("")}</div></section>`).join("")}
function openAdmin(){modal.classList.add("open");modal.setAttribute("aria-hidden","false");showAdmin()}
function closeAdmin(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");closePasswordDialog()}
adminButton.onclick=async()=>{await syncAdminSession();openAdmin()};document.querySelector("#closeAdmin").onclick=closeAdmin;
document.querySelector("#loginForm").onsubmit=async e=>{e.preventDefault();const error=document.querySelector("#loginError");if(!isHosted){error.textContent="Admin access is available on the secure online website.";return}const response=await fetch("/api/auth",{method:"POST",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({email:document.querySelector("#adminEmail").value.trim().toLowerCase(),password:document.querySelector("#adminPassword").value})});const data=await response.json();if(response.ok){sessionStorage.setItem("vk_admin","yes");setAdminIdentity(data.name);scheduleSessionEnd(data.expires);e.target.reset();error.textContent="";showAdmin()}else error.textContent="Incorrect email or password."};
document.querySelector("#logoutAdmin").onclick=async()=>{if(isHosted)await fetch("/api/auth",{method:"DELETE",credentials:"same-origin"});clearTimeout(sessionTimer);sessionStorage.removeItem("vk_admin");setAdminIdentity();showAdmin()};
const passwordDialog=document.querySelector("#passwordDialog"),passwordForm=document.querySelector("#passwordForm"),passwordMessage=document.querySelector("#passwordMessage");
function closePasswordDialog(){passwordForm.reset();passwordMessage.textContent="";passwordDialog.hidden=true}
document.querySelector("#togglePassword").onclick=()=>{passwordDialog.hidden=false;document.querySelector("#currentPassword").focus()};
document.querySelector("#cancelPassword").onclick=closePasswordDialog;
passwordDialog.onclick=e=>{if(e.target===passwordDialog)closePasswordDialog()};
window.addEventListener("pageshow",closeAdmin);
syncAdminSession();
passwordForm.onsubmit=async e=>{e.preventDefault();const currentPassword=document.querySelector("#currentPassword").value,newPassword=document.querySelector("#newPassword").value,confirmation=document.querySelector("#confirmPassword").value;if(newPassword!==confirmation){passwordMessage.textContent="New passwords do not match.";return}const response=await fetch("/api/auth",{method:"PATCH",headers:{"content-type":"application/json"},credentials:"same-origin",body:JSON.stringify({currentPassword,newPassword})});const result=await response.json();if(!response.ok){passwordMessage.textContent=result.error||"Password could not be changed.";return}sessionStorage.removeItem("vk_admin");closePasswordDialog();alert("Password changed successfully. Please sign in again.");showAdmin()};
document.querySelector("#categoryForm").onsubmit=e=>{e.preventDefault();const name=document.querySelector("#categoryName").value.trim();if(name&&!menu[name])menu[name]=[];e.target.reset();saveMenu()};
document.querySelector("#dishForm").onsubmit=e=>{e.preventDefault();const name=document.querySelector("#dishName").value.trim(),category=categorySelect.value,description=document.querySelector("#dishDescription").value.trim(),editing=document.querySelector("#editingDish").value,error=document.querySelector("#dishError");if(!name){error.textContent="Enter a dish name.";document.querySelector("#dishName").focus();return}if(!category||!menu[category]){error.textContent="Add or select a valid category first.";categorySelect.focus();return}error.textContent="";if(editing){const [oldCategory,oldName]=editing.split("|");menu[oldCategory]=menu[oldCategory].filter(d=>d.name!==oldName)}const existing=menu[category].find(d=>d.name===name);if(existing)existing.description=description;else menu[category].push({name,description});e.target.reset();document.querySelector("#dishFormTitle").textContent="Add a dish";saveMenu()};
const confirmDialog=document.querySelector("#confirmDialog"),confirmTitle=document.querySelector("#confirmTitle"),confirmMessage=document.querySelector("#confirmMessage");
function confirmRemoval(title,message){return new Promise(resolve=>{const previousFocus=document.activeElement;confirmTitle.textContent=title;confirmMessage.textContent=message;confirmDialog.hidden=false;document.querySelector("#confirmDelete").focus();const finish=value=>{confirmDialog.hidden=true;document.querySelector("#confirmDelete").onclick=null;document.querySelector("#cancelDelete").onclick=null;previousFocus?.focus();resolve(value)};document.querySelector("#confirmDelete").onclick=()=>finish(true);document.querySelector("#cancelDelete").onclick=()=>finish(false)})}
confirmDialog.onclick=e=>{if(e.target===confirmDialog)document.querySelector("#cancelDelete").click()};
document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!confirmDialog.hidden)document.querySelector("#cancelDelete").click()});
adminList.onclick=async e=>{const target=e.target;if(target.dataset.deleteCategory){const category=target.dataset.deleteCategory,dishCount=menu[category].length;if(await confirmRemoval(`Delete “${category}”?`,`This will permanently remove the category and all ${dishCount} dish${dishCount===1?"":"es"} inside it.`)){delete menu[category];saveMenu()}return}if(target.dataset.deleteDish){const [c,n]=target.dataset.deleteDish.split("|");if(await confirmRemoval(`Delete “${n}”?`,`This will permanently remove the dish from ${c}.`)){menu[c]=menu[c].filter(d=>d.name!==n);saveMenu()}return}if(target.dataset.editDish){const [c,n]=target.dataset.editDish.split("|"),dish=menu[c].find(d=>d.name===n);document.querySelector("#editingDish").value=`${c}|${n}`;document.querySelector("#dishName").value=dish.name;categorySelect.value=c;document.querySelector("#dishDescription").value=dish.description;document.querySelector("#dishFormTitle").textContent="Edit dish & description";document.querySelector("#dishName").focus()}};
